-- SummitWar initial schema. All money is integer cents and all season times are UTC.
create extension if not exists pgcrypto;

create type public.listing_status as enum ('pending_payment', 'pending_review', 'approved', 'hidden', 'suspended');
create type public.season_status as enum ('upcoming', 'active', 'closed');
create type public.payment_status as enum ('pending', 'succeeded', 'failed', 'refunded');
create type public.ranking_event_type as enum ('joined', 'climbed', 'summit_taken', 'summit_reclaimed', 'overtaken', 'season_started');

create table public.seasons (
  id uuid primary key default gen_random_uuid(),
  season_number bigint generated by default as identity unique,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status public.season_status not null default 'upcoming',
  winner_listing_id uuid,
  runner_up_listing_id uuid,
  winning_spend_cents bigint not null default 0 check (winning_spend_cents >= 0),
  winning_altitude_meters bigint not null default 0 check (winning_altitude_meters >= 0),
  winner_clicks bigint not null default 0 check (winner_clicks >= 0),
  winner_summit_seconds bigint not null default 0 check (winner_summit_seconds >= 0),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);
create unique index seasons_one_active_idx on public.seasons (status) where status = 'active';
create index seasons_dates_idx on public.seasons (starts_at desc, ends_at desc);

create table public.listings (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (char_length(name) between 1 and 80),
  tagline text not null default '' check (char_length(tagline) <= 160),
  description text not null default '' check (char_length(description) <= 5000),
  website_url text not null,
  normalized_url text not null unique,
  logo_path text,
  logo_url text,
  founder_name text not null default '' check (char_length(founder_name) <= 100),
  founder_x_handle text not null default '' check (char_length(founder_x_handle) <= 32),
  category text not null default 'Other' check (char_length(category) <= 64),
  launch_year smallint not null check (launch_year between 1980 and 2100),
  status public.listing_status not null default 'pending_payment',
  current_season_id uuid references public.seasons(id) on delete set null,
  current_season_spend_cents bigint not null default 0 check (current_season_spend_cents >= 0 and current_season_spend_cents % 100 = 0),
  lifetime_spend_cents bigint not null default 0 check (lifetime_spend_cents >= 0 and lifetime_spend_cents % 100 = 0),
  current_rank integer check (current_rank is null or current_rank > 0),
  first_reached_current_spend_at timestamptz not null default now(),
  summit_wins integer not null default 0 check (summit_wins >= 0),
  total_summit_seconds bigint not null default 0 check (total_summit_seconds >= 0),
  lifetime_profile_views bigint not null default 0 check (lifetime_profile_views >= 0),
  total_outbound_clicks bigint not null default 0 check (total_outbound_clicks >= 0),
  is_demo boolean not null default false,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index listings_public_ranking_idx on public.listings (status, current_season_spend_cents desc, first_reached_current_spend_at asc);
create index listings_category_idx on public.listings (status, category);
create index listings_clicks_idx on public.listings (status, total_outbound_clicks desc);
create index listings_lifetime_spend_idx on public.listings (status, lifetime_spend_cents desc);
alter table public.seasons add constraint seasons_winner_listing_id_fkey foreign key (winner_listing_id) references public.listings(id) on delete set null;
alter table public.seasons add constraint seasons_runner_up_listing_id_fkey foreign key (runner_up_listing_id) references public.listings(id) on delete set null;

create table public.listing_owners (
  listing_id uuid not null references public.listings(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (listing_id, owner_id)
);
create index listing_owners_owner_idx on public.listing_owners(owner_id);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete restrict,
  season_id uuid references public.seasons(id) on delete set null,
  provider text not null default 'dodo',
  provider_checkout_id text unique,
  provider_payment_id text unique,
  payer_email text not null,
  amount_cents bigint not null check (amount_cents >= 100 and amount_cents % 100 = 0),
  currency text not null default 'USD' check (currency = upper(currency)),
  status public.payment_status not null default 'pending',
  verified boolean not null default false,
  requested_rank integer,
  quote_snapshot jsonb not null default '{}'::jsonb,
  failure_code text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index payments_listing_idx on public.payments(listing_id, created_at desc);
create index payments_status_idx on public.payments(status, created_at desc);
create index payments_completed_idx on public.payments(completed_at desc) where status = 'succeeded';

create table public.webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  payload_digest text not null,
  status text not null default 'processing' check (status in ('processing', 'processed', 'ignored', 'failed')),
  error_message text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(provider, provider_event_id)
);
create index webhook_events_created_idx on public.webhook_events(created_at desc);

create table public.ranking_events (
  id uuid primary key default gen_random_uuid(),
  season_id uuid references public.seasons(id) on delete set null,
  listing_id uuid references public.listings(id) on delete set null,
  displaced_listing_id uuid references public.listings(id) on delete set null,
  payment_id uuid references public.payments(id) on delete set null,
  event_type public.ranking_event_type not null,
  message text not null,
  old_rank integer,
  new_rank integer,
  amount_cents bigint,
  altitude_meters bigint,
  created_at timestamptz not null default now()
);
create index ranking_events_live_idx on public.ranking_events(created_at desc);
create index ranking_events_listing_idx on public.ranking_events(listing_id, created_at desc);

create table public.rank_snapshots (
  id bigint generated by default as identity primary key,
  season_id uuid not null references public.seasons(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  rank integer not null check (rank > 0),
  spend_cents bigint not null check (spend_cents >= 0),
  altitude_meters bigint not null check (altitude_meters >= 0),
  captured_at timestamptz not null default now()
);
create index rank_snapshots_listing_idx on public.rank_snapshots(listing_id, captured_at);
create index rank_snapshots_season_idx on public.rank_snapshots(season_id, captured_at);

create table public.summit_holds (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  seconds_held bigint generated always as (
    greatest(0, extract(epoch from (coalesce(ended_at, started_at) - started_at))::bigint)
  ) stored
);
create unique index summit_holds_one_open_idx on public.summit_holds(season_id) where ended_at is null;
create index summit_holds_listing_idx on public.summit_holds(listing_id, started_at desc);

create table public.profile_view_events (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  visitor_hash text not null,
  occurred_at timestamptz not null default now(),
  bucket_start timestamptz not null,
  unique(listing_id, visitor_hash, bucket_start)
);
create index profile_view_events_time_idx on public.profile_view_events(occurred_at desc);

create table public.outbound_click_events (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  visitor_hash text not null,
  occurred_at timestamptz not null default now(),
  bucket_start timestamptz not null,
  unique(listing_id, visitor_hash, bucket_start)
);
create index outbound_click_events_time_idx on public.outbound_click_events(occurred_at desc);

create table public.daily_metrics (
  metric_date date primary key,
  revenue_cents bigint not null default 0,
  climbs bigint not null default 0,
  profile_views bigint not null default 0,
  outbound_clicks bigint not null default 0,
  unique_visitors bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.site_metrics (
  singleton boolean primary key default true check (singleton),
  verified_revenue_cents bigint not null default 0,
  payment_count bigint not null default 0,
  largest_payment_cents bigint not null default 0,
  paid_startups bigint not null default 0,
  unique_visitors bigint not null default 0,
  profile_views bigint not null default 0,
  outbound_clicks bigint not null default 0,
  online_visitors bigint not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.site_metrics(singleton) values (true);

create table public.presence_sessions (
  visitor_hash text primary key,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index presence_sessions_seen_idx on public.presence_sessions(last_seen_at desc);

create table public.visitor_registry (
  visitor_hash text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table public.notification_preferences (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  successful_climb boolean not null default true,
  overtaken boolean not null default true,
  summit_reached boolean not null default true,
  upcoming_avalanche boolean not null default true,
  season_victory boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.listing_contacts (
  listing_id uuid not null references public.listings(id) on delete cascade,
  email text not null,
  owner_id uuid references auth.users(id) on delete set null,
  verified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  primary key(listing_id, email)
);

create table public.notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete cascade,
  season_id uuid references public.seasons(id) on delete cascade,
  template text not null,
  recipient_digest text not null,
  delivered_at timestamptz not null default now(),
  unique(listing_id, season_id, template, recipient_digest)
);

create table public.testimonials (
  id uuid primary key default gen_random_uuid(),
  quote text not null check (char_length(quote) between 5 and 600),
  founder_name text not null,
  startup_name text not null,
  founder_x_handle text,
  is_published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.moderation_reports (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  reporter_hash text,
  reason text not null,
  details text not null default '',
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index moderation_reports_status_idx on public.moderation_reports(status, created_at desc);

create table public.admin_audit_log (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid references auth.users(id) on delete set null,
  admin_email text not null,
  action text not null,
  target_type text not null,
  target_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);
create index admin_audit_log_created_idx on public.admin_audit_log(created_at desc);

create table public.site_settings (
  key text primary key,
  value jsonb not null,
  is_public boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.site_settings(key, value, is_public) values
  ('minimum_bid_cents', '100'::jsonb, true),
  ('sponsorship_disclosure', '"Placements are sponsored. Payments are normally non-refundable and rankings can change at any time."'::jsonb, true);

create table public.rate_limit_buckets (
  bucket_key text not null,
  window_start timestamptz not null,
  request_count integer not null default 1,
  primary key(bucket_key, window_start)
);

create or replace function public.reject_immutable_changes()
returns trigger language plpgsql as $$
begin
  raise exception 'This event ledger is immutable';
end;
$$;
create trigger ranking_events_immutable before update or delete on public.ranking_events
for each row execute function public.reject_immutable_changes();

create or replace function public.get_public_site_stats()
returns table (
  verified_revenue_cents bigint,
  revenue_today_cents bigint,
  revenue_season_cents bigint,
  payment_count bigint,
  average_payment_cents bigint,
  largest_payment_cents bigint,
  paid_startups bigint,
  online_visitors bigint,
  unique_visitors bigint,
  profile_views bigint,
  outbound_clicks bigint,
  total_climbs bigint,
  startups_competing bigint
)
language sql stable security invoker set search_path = '' as $$
  select
    s.verified_revenue_cents,
    coalesce(d.revenue_cents, 0),
    coalesce((select sum(l.current_season_spend_cents) from public.listings l where l.status = 'approved'), 0),
    s.payment_count,
    case when s.payment_count = 0 then 0 else s.verified_revenue_cents / s.payment_count end,
    s.largest_payment_cents,
    s.paid_startups,
    s.online_visitors,
    s.unique_visitors,
    s.profile_views,
    s.outbound_clicks,
    s.payment_count,
    (select count(*) from public.listings l where l.status = 'approved' and l.current_season_spend_cents > 0)
  from public.site_metrics s
  left join public.daily_metrics d on d.metric_date = (now() at time zone 'utc')::date
  where s.singleton = true;
$$;

create or replace function public.consume_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare
  v_window timestamptz := to_timestamp(floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds);
  v_count integer;
begin
  insert into public.rate_limit_buckets(bucket_key, window_start, request_count)
  values (p_key, v_window, 1)
  on conflict (bucket_key, window_start) do update
    set request_count = public.rate_limit_buckets.request_count + 1
  returning request_count into v_count;
  return v_count <= p_limit;
end;
$$;

create or replace function public.record_profile_view(p_listing_id uuid, p_visitor_hash text)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare
  v_bucket timestamptz := date_trunc('hour', now());
  v_inserted bigint;
begin
  insert into public.profile_view_events(listing_id, visitor_hash, bucket_start)
  values (p_listing_id, p_visitor_hash, v_bucket)
  on conflict do nothing returning id into v_inserted;
  if v_inserted is null then return false; end if;
  update public.listings set lifetime_profile_views = lifetime_profile_views + 1 where id = p_listing_id;
  update public.site_metrics set profile_views = profile_views + 1, updated_at = now() where singleton;
  insert into public.daily_metrics(metric_date, profile_views) values ((now() at time zone 'utc')::date, 1)
  on conflict (metric_date) do update set profile_views = public.daily_metrics.profile_views + 1, updated_at = now();
  return true;
end;
$$;

create or replace function public.record_outbound_click(p_listing_id uuid, p_visitor_hash text)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare
  v_bucket timestamptz := date_trunc('hour', now());
  v_inserted bigint;
begin
  insert into public.outbound_click_events(listing_id, visitor_hash, bucket_start)
  values (p_listing_id, p_visitor_hash, v_bucket)
  on conflict do nothing returning id into v_inserted;
  if v_inserted is null then return false; end if;
  update public.listings set total_outbound_clicks = total_outbound_clicks + 1 where id = p_listing_id;
  update public.site_metrics set outbound_clicks = outbound_clicks + 1, updated_at = now() where singleton;
  insert into public.daily_metrics(metric_date, outbound_clicks) values ((now() at time zone 'utc')::date, 1)
  on conflict (metric_date) do update set outbound_clicks = public.daily_metrics.outbound_clicks + 1, updated_at = now();
  return true;
end;
$$;

create or replace function public.heartbeat_presence(p_visitor_hash text)
returns bigint language plpgsql security invoker set search_path = '' as $$
declare
  v_new_hash text;
  v_online bigint;
begin
  insert into public.visitor_registry(visitor_hash) values (p_visitor_hash)
  on conflict (visitor_hash) do update set last_seen_at = now()
  returning case when first_seen_at = last_seen_at then visitor_hash end into v_new_hash;
  insert into public.presence_sessions(visitor_hash, last_seen_at) values(p_visitor_hash, now())
  on conflict (visitor_hash) do update set last_seen_at = now();
  delete from public.presence_sessions where last_seen_at < now() - interval '2 minutes';
  select count(*) into v_online from public.presence_sessions;
  update public.site_metrics set online_visitors = v_online,
    unique_visitors = (select count(*) from public.visitor_registry), updated_at = now() where singleton;
  return v_online;
end;
$$;

create or replace function public.apply_verified_payment(
  p_provider_event_id text,
  p_provider_payment_id text,
  p_payment_id uuid,
  p_amount_cents bigint,
  p_currency text,
  p_payload_digest text,
  p_occurred_at timestamptz default now()
)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_payment public.payments%rowtype;
  v_listing public.listings%rowtype;
  v_season_id uuid;
  v_webhook_id uuid;
  v_old_rank integer;
  v_new_rank integer;
  v_previous_summit_id uuid;
  v_previous_summit_name text;
  v_event_type public.ranking_event_type;
  v_message text;
begin
  insert into public.webhook_events(provider, provider_event_id, event_type, payload_digest)
  values ('dodo', p_provider_event_id, 'payment.succeeded', p_payload_digest)
  on conflict (provider, provider_event_id) do nothing returning id into v_webhook_id;
  if v_webhook_id is null then
    return jsonb_build_object('duplicate', true);
  end if;

  select * into v_payment from public.payments where id = p_payment_id for update;
  if not found then raise exception 'Unknown checkout payment'; end if;
  if v_payment.status = 'succeeded' then
    update public.webhook_events set status = 'ignored', processed_at = now() where id = v_webhook_id;
    return jsonb_build_object('duplicate', true, 'payment_id', v_payment.id);
  end if;
  if v_payment.amount_cents <> p_amount_cents or upper(v_payment.currency) <> upper(p_currency) then
    raise exception 'Webhook amount or currency does not match checkout';
  end if;
  if exists(select 1 from public.payments where provider_payment_id = p_provider_payment_id and id <> p_payment_id) then
    raise exception 'Provider payment already credited';
  end if;

  select id into v_season_id from public.seasons
    where status = 'active' and p_occurred_at between starts_at and ends_at
    for update;
  if v_season_id is null then raise exception 'No active season for payment time'; end if;

  perform id from public.listings where status in ('approved', 'pending_payment', 'pending_review') order by id for update;
  select id, name into v_previous_summit_id, v_previous_summit_name
    from public.listings where status = 'approved' and current_rank = 1 limit 1;
  select * into v_listing from public.listings where id = v_payment.listing_id for update;
  v_old_rank := v_listing.current_rank;

  update public.listings set
    status = 'approved',
    approved_at = coalesce(approved_at, p_occurred_at),
    current_season_id = v_season_id,
    current_season_spend_cents = case when current_season_id = v_season_id then current_season_spend_cents else 0 end + p_amount_cents,
    lifetime_spend_cents = lifetime_spend_cents + p_amount_cents,
    first_reached_current_spend_at = p_occurred_at,
    updated_at = now()
  where id = v_payment.listing_id
  returning * into v_listing;

  with ranked as (
    select id, row_number() over(order by current_season_spend_cents desc, first_reached_current_spend_at asc, id asc)::integer as new_rank
    from public.listings where status = 'approved' and current_season_spend_cents > 0
  )
  update public.listings l set current_rank = r.new_rank from ranked r where l.id = r.id;
  update public.listings set current_rank = null where status <> 'approved' or current_season_spend_cents = 0;
  select current_rank into v_new_rank from public.listings where id = v_payment.listing_id;

  update public.payments set status = 'succeeded', verified = true, season_id = v_season_id,
    provider_payment_id = p_provider_payment_id, completed_at = p_occurred_at, updated_at = now()
  where id = v_payment.id;

  insert into public.listing_contacts(listing_id, email, verified_at)
  values (v_listing.id, lower(v_payment.payer_email), p_occurred_at)
  on conflict (listing_id, email) do update set verified_at = excluded.verified_at;

  if v_new_rank = 1 and v_previous_summit_id is distinct from v_listing.id then
    update public.summit_holds set ended_at = p_occurred_at where season_id = v_season_id and ended_at is null;
    insert into public.summit_holds(season_id, listing_id, started_at) values (v_season_id, v_listing.id, p_occurred_at);
    v_event_type := 'summit_taken';
    v_message := case when v_previous_summit_id is null then v_listing.name || ' captured the summit.' else v_listing.name || ' pushed ' || v_previous_summit_name || ' off the summit.' end;
  elsif v_old_rank is null then
    v_event_type := 'joined';
    v_message := v_listing.name || ' joined Base Camp for $' || (p_amount_cents / 100)::text || '.';
  else
    v_event_type := 'climbed';
    v_message := v_listing.name || ' climbed from #' || v_old_rank::text || ' to #' || v_new_rank::text || '.';
  end if;

  insert into public.ranking_events(season_id, listing_id, displaced_listing_id, payment_id, event_type, message, old_rank, new_rank, amount_cents, altitude_meters, created_at)
  values (v_season_id, v_listing.id, case when v_new_rank = 1 then v_previous_summit_id end, v_payment.id, v_event_type, v_message, v_old_rank, v_new_rank, p_amount_cents, v_listing.current_season_spend_cents, p_occurred_at);

  insert into public.rank_snapshots(season_id, listing_id, rank, spend_cents, altitude_meters, captured_at)
  select v_season_id, id, current_rank, current_season_spend_cents, current_season_spend_cents, p_occurred_at
  from public.listings where status = 'approved' and current_rank is not null;

  update public.site_metrics set
    verified_revenue_cents = verified_revenue_cents + p_amount_cents,
    payment_count = payment_count + 1,
    largest_payment_cents = greatest(largest_payment_cents, p_amount_cents),
    paid_startups = (select count(*) from public.listings where lifetime_spend_cents > 0),
    updated_at = now()
  where singleton;
  insert into public.daily_metrics(metric_date, revenue_cents, climbs)
  values ((p_occurred_at at time zone 'utc')::date, p_amount_cents, 1)
  on conflict (metric_date) do update set revenue_cents = public.daily_metrics.revenue_cents + p_amount_cents, climbs = public.daily_metrics.climbs + 1, updated_at = now();
  update public.webhook_events set status = 'processed', processed_at = now() where id = v_webhook_id;

  return jsonb_build_object('duplicate', false, 'listing_id', v_listing.id, 'displaced_listing_id', case when v_new_rank = 1 then v_previous_summit_id end, 'old_rank', v_old_rank, 'new_rank', v_new_rank, 'season_id', v_season_id);
end;
$$;

create or replace function public.rotate_weekly_season(p_now timestamptz default now())
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_active public.seasons%rowtype;
  v_winner public.listings%rowtype;
  v_runner public.listings%rowtype;
  v_new_id uuid;
  v_start timestamptz := date_trunc('week', p_now at time zone 'utc') at time zone 'utc';
  v_end timestamptz := (date_trunc('week', p_now at time zone 'utc') + interval '7 days') at time zone 'utc' - interval '1 millisecond';
begin
  perform pg_advisory_xact_lock(hashtext('summitwar-season-rotation'));
  select * into v_active from public.seasons where status = 'active' for update;
  if found and p_now <= v_active.ends_at then return jsonb_build_object('rotated', false, 'season_id', v_active.id); end if;
  if found then
    select * into v_winner from public.listings where status = 'approved' and current_rank = 1;
    select * into v_runner from public.listings where status = 'approved' and current_rank = 2;
    update public.summit_holds set ended_at = least(p_now, v_active.ends_at) where season_id = v_active.id and ended_at is null;
    if v_winner.id is not null then
      update public.listings set summit_wins = summit_wins + 1,
        total_summit_seconds = total_summit_seconds + coalesce((select sum(extract(epoch from (ended_at - started_at)))::bigint from public.summit_holds where season_id = v_active.id and listing_id = v_winner.id), 0)
      where id = v_winner.id;
    end if;
    update public.seasons set status = 'closed', winner_listing_id = v_winner.id, runner_up_listing_id = v_runner.id,
      winning_spend_cents = coalesce(v_winner.current_season_spend_cents, 0), winning_altitude_meters = coalesce(v_winner.current_season_spend_cents, 0),
      winner_clicks = coalesce(v_winner.total_outbound_clicks, 0),
      winner_summit_seconds = coalesce((select sum(extract(epoch from (ended_at - started_at)))::bigint from public.summit_holds where season_id = v_active.id and listing_id = v_winner.id), 0),
      closed_at = p_now where id = v_active.id;
  end if;
  insert into public.seasons(starts_at, ends_at, status) values(v_start, v_end, 'active') returning id into v_new_id;
  update public.listings set current_season_id = v_new_id, current_season_spend_cents = 0, current_rank = null, first_reached_current_spend_at = v_start, updated_at = now();
  insert into public.ranking_events(season_id, event_type, message, created_at) values(v_new_id, 'season_started', 'A new Avalanche Season has begun.', p_now);
  return jsonb_build_object('rotated', true, 'season_id', v_new_id, 'closed_season_id', v_active.id, 'winner_listing_id', v_winner.id);
end;
$$;

alter table public.listings enable row level security;
alter table public.listing_owners enable row level security;
alter table public.seasons enable row level security;
alter table public.payments enable row level security;
alter table public.webhook_events enable row level security;
alter table public.ranking_events enable row level security;
alter table public.rank_snapshots enable row level security;
alter table public.summit_holds enable row level security;
alter table public.profile_view_events enable row level security;
alter table public.outbound_click_events enable row level security;
alter table public.daily_metrics enable row level security;
alter table public.site_metrics enable row level security;
alter table public.presence_sessions enable row level security;
alter table public.visitor_registry enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.listing_contacts enable row level security;
alter table public.notification_deliveries enable row level security;
alter table public.testimonials enable row level security;
alter table public.moderation_reports enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.site_settings enable row level security;
alter table public.rate_limit_buckets enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke execute on all functions in schema public from public, anon, authenticated;

grant select on public.listings, public.seasons, public.ranking_events, public.rank_snapshots, public.daily_metrics, public.site_metrics, public.testimonials, public.site_settings to anon, authenticated;
grant select on public.listing_owners, public.payments, public.notification_preferences, public.summit_holds to authenticated;
grant update(name, tagline, description, category, logo_path, logo_url, founder_name, founder_x_handle, launch_year, updated_at) on public.listings to authenticated;
grant insert, update on public.notification_preferences to authenticated;
grant execute on function public.get_public_site_stats() to anon, authenticated;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;
grant execute on function public.record_profile_view(uuid, text) to service_role;
grant execute on function public.record_outbound_click(uuid, text) to service_role;
grant execute on function public.heartbeat_presence(text) to service_role;
grant execute on function public.apply_verified_payment(text, text, uuid, bigint, text, text, timestamptz) to service_role;
grant execute on function public.rotate_weekly_season(timestamptz) to service_role;

create policy listings_public_read on public.listings for select to anon, authenticated using (status = 'approved');
create policy listings_owner_read on public.listings for select to authenticated using (exists(select 1 from public.listing_owners o where o.listing_id = id and o.owner_id = (select auth.uid())));
create policy listings_owner_update on public.listings for update to authenticated using (exists(select 1 from public.listing_owners o where o.listing_id = id and o.owner_id = (select auth.uid()))) with check (exists(select 1 from public.listing_owners o where o.listing_id = id and o.owner_id = (select auth.uid())));
create policy owners_self_read on public.listing_owners for select to authenticated using (owner_id = (select auth.uid()));
create policy seasons_public_read on public.seasons for select to anon, authenticated using (true);
create policy ranking_events_public_read on public.ranking_events for select to anon, authenticated using (true);
create policy rank_snapshots_public_read on public.rank_snapshots for select to anon, authenticated using (true);
create policy daily_metrics_public_read on public.daily_metrics for select to anon, authenticated using (true);
create policy site_metrics_public_read on public.site_metrics for select to anon, authenticated using (true);
create policy testimonials_public_read on public.testimonials for select to anon, authenticated using (is_published);
create policy settings_public_read on public.site_settings for select to anon, authenticated using (is_public);
create policy payments_owner_read on public.payments for select to authenticated using (exists(select 1 from public.listing_owners o where o.listing_id = payments.listing_id and o.owner_id = (select auth.uid())));
create policy summit_holds_public_read on public.summit_holds for select to authenticated using (true);
create policy preferences_self_read on public.notification_preferences for select to authenticated using (owner_id = (select auth.uid()));
create policy preferences_self_insert on public.notification_preferences for insert to authenticated with check (owner_id = (select auth.uid()));
create policy preferences_self_update on public.notification_preferences for update to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('startup-logos', 'startup-logos', true, 2097152, array['image/png','image/jpeg','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
create policy logo_public_read on storage.objects for select to anon, authenticated using (bucket_id = 'startup-logos');
create policy logo_owner_insert on storage.objects for insert to authenticated with check (
  bucket_id = 'startup-logos' and exists(
    select 1 from public.listing_owners o where o.owner_id = (select auth.uid()) and (storage.foldername(name))[1] = o.listing_id::text
  )
);
create policy logo_owner_update on storage.objects for update to authenticated using (
  bucket_id = 'startup-logos' and exists(
    select 1 from public.listing_owners o where o.owner_id = (select auth.uid()) and (storage.foldername(name))[1] = o.listing_id::text
  )
) with check (
  bucket_id = 'startup-logos' and exists(
    select 1 from public.listing_owners o where o.owner_id = (select auth.uid()) and (storage.foldername(name))[1] = o.listing_id::text
  )
);

alter publication supabase_realtime add table public.ranking_events;
alter publication supabase_realtime add table public.listings;
